port: 2802

httpPort: 8080

scenarios:
 - bridge

architectServers:
 - hostname: localhost
   port: 10000
 - hostname: localhost
   port: 10001
 - hostname: localhost
   port: 10002
 - hostname: localhost
   port: 10003
 - hostname: localhost
   port: 10004
 - hostname: localhost
   port: 10005

database:
  url: "jdbc:mariadb://localhost:3306/RANDOMOPTIMALBRIDGE"
  username: "minecraft"
